version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "fetch-bayesball-data-dev"
s3_bucket = <create-your-own-bucket>
s3_prefix = "fetch-bayesball-data-dev"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "RapidApiKey=your-api-key-here Env=dev"


[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "fetch-bayesball-data-prod"
s3_bucket = <create-your-own-bucket>
s3_prefix = "fetch-bayesball-data-prod"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "RapidApiKey=your-api-key-here Env=prod"
